####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
#███████╗██╗      █████╗ ██╗   ██╗ █████╗     ██╗    ██╗██╗███╗   ██╗███████╗                    | #
#██╔════╝██║     ██╔══██╗██║   ██║██╔══██╗    ██║    ██║██║████╗  ██║██╔════╝                    | #
#███████╗██║     ███████║██║   ██║███████║    ██║ █╗ ██║██║██╔██╗ ██║███████╗                    | #
#╚════██║██║     ██╔══██║╚██╗ ██╔╝██╔══██║    ██║███╗██║██║██║╚██╗██║╚════██║                    | #
#███████║███████╗██║  ██║ ╚████╔╝ ██║  ██║    ╚███╔███╔╝██║██║ ╚████║███████║                    | #
#╚══════╝╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚═╝  ╚═╝     ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚══════╝                    | #
#            ██████╗ ███████╗ █████╗ ███████╗███████╗███████╗████████╗███████╗                   | #
#            ██╔══██╗██╔════╝██╔══██╗██╔════╝██╔════╝██╔════╝╚══██╔══╝██╔════╝                   | #
#█████╗█████╗██████╔╝█████╗  ███████║███████╗███████╗█████╗     ██║   ███████╗█████╗█████╗       | #
#╚════╝╚════╝██╔══██╗██╔══╝  ██╔══██║╚════██║╚════██║██╔══╝     ██║   ╚════██║╚════╝╚════╝        | #
#            ██║  ██║███████╗██║  ██║███████║███████║███████╗   ██║   ███████║                   | #
#            ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝   ╚═╝   ╚══════╝                   | #
#                                                                                                | #
#                                                                                                | #
#       Документация и прочее:                                                                   | #
#        ==> https://github.com/slavaWins/reassets                                               | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

name: "reassets"

debug: false #дебаг для разработчика
lang: en #язык


resource-pack-send-enabled: false # отправлять игрокам ресурспак
resource-pack-url: "http://minehelper.test/uploads/xz.zip?dl=1" # Ссылка на ресурспак, обновляется сама


upload-enabled: false # отправлять на юрл респак когда он обновился?
upload-url: http://minehelper.test/upload.php?token=xxx # на какою эндпонит